name: Node Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  node-tests:
    uses: alleyinteractive/.github/.github/workflows/node-tests.yml@main
    with:
      run-build: false
